import Header from '@/components/Header';
import { Lato } from 'next/font/google';
import '../../globals.css';

const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] });

export async function generateMetadata({ params }) {
  return {
    title: `${
      params?.uri
        ? `${params?.uri?.[0]?.toUpperCase()}${params?.uri?.substring(1)}`
        : ''
    }`,
    description: 'Generated by create next app',
  };
}

export default function RootLayout({ params, children }) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
